version: "3.9"
services:
  server:
    build: ./backend
    ports:
    - "8080:8080"
    environment:
      FLASK_ENV: development

  web:
    build: ./frontend
    ports:
    - "5173:5173"
    environment:
      VITE_BACKEND_URL: "http://server:8080"
    depends_on:
    - server